version: '2'
services:
    python:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        container_name : yolo
        image: "tuananhbk/yolo:gpu"
        ports:
            - "8889:8889"
        volumes:
            - ".:/data"
        ipc: host
        user: anh
        working_dir: /data
        tty: true